version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://db:27017/toys-hub
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=toys-hub
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - '3000:3000'
#     environment:
#       - MONGODB_URI=mongodb://db:27017/toys-hub
#     depends_on:
#       - db
#   db:
#     build: ./db
#     environment:
#       - MONGO_INITDB_DATABASE=toys-hub
#     volumes:
#       - dbdata:/data/db

# volumes:
#   dbdata:
